
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat, Roboto, Inter as FontSans } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster";

const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--montserrat',
  subsets: ['latin']
})

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700'],
  variable: '--roboto',
  subsets: ['latin']
})

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Browser Power Toys",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="2XhCdH264JXK91qzzDi6-nRDidcVzyEfJPJ4PULnugs" />
      </head>
      <body
        className={`${roboto.variable} ${montserrat.variable} ${fontSans.variable} font-sans antialiased `}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
